### ISSUE TITLE
[Release]v0.4.0

### ISSUE THREAD

**Issue by snamiki1212** [snamiki1212/canada-immigration-scheduler#14]
- from: https://github.com/snamiki1212/canada-immigration-scheduler/issues/8#issuecomment-770278623

## Tasks

Features
- [x] Split calendar into User / Generated
- [x] Story line name to become more understandable name
- [x] UPDATE: copy/remove story
- [x] UPDATE: add/remove event in calendar

Non-Features
- [x] Implement redux
- [x] ~~normalize store~~ => maybe no need now
