### ISSUE TITLE
[Release] v0.3.0 New Features

### ISSUE THREAD

**Issue by snamiki1212** [snamiki1212/canada-immigration-scheduler#9]
## Tasks
- [x] Add auto generation feature https://github.com/snamiki1212/canada-immigration-scheduler/pull/12
- [x] Add 2 lines about working holiday 
- [x] Fix design to add space between event

## Ref
- https://github.com/snamiki1212/canada-immigration-scheduler/issues/8#issuecomment-767907107

**Comment by snamiki1212** [comment]
close by https://github.com/snamiki1212/canada-immigration-scheduler/pull/10
